apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmmbs-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmmbs-web
  template:
    metadata:
      labels:
        app: dmmbs-web
    spec:
      containers:
      - name: dmmbs-web-cont
        image: dmmbs-web
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmmbs-was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmmbs-was
  template:
    metadata:
      labels:
        app: dmmbs-was
    spec:
      containers:
      - name: dmmbs-was-cont
        image: dmmbs-was
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dmmbs-was
spec:
  selector:
    app: dmmbs-was
  ports:
    - name: was
      protocol: TCP
      port: 8100
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dmmbs-web
spec:
  selector:
    app: dmmbs-web
  ports:
    - name: web
      protocol: TCP
      port: 8100
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dmmbs-lb
spec:
  ports:
  - port: 80
    targetPort: 8100
  selector:
    app: dmmbs-lb
  type: LoadBalancer
